from django.core.management.base import BaseCommand
from website.models import Faculty, University


members = [
    {
        "first_name": "Martin",
        "last_name": "Vancl",
        "email": "martin@vancl.me",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Matematicko-fyzik\u00e1ln\u00ed fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "+420 773 551 407",
        "member_since": "4. 4. 2021",
        "last_prolonged": "4. 4. 2021",
        "lifetime_since": "4. 4. 2021",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Luana",
        "last_name": "Toscano",
        "email": "lutosc9s@gmail.com",
        "lifelong_membership": False,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "28. 9. 2022",
        "photos_allowed": True,
        "phone": "+39 3512 474 050",
        "member_since": "28. 9. 2021",
        "last_prolonged": "28. 9. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Daniel",
        "last_name": "Majer",
        "email": "96majer96@gmail.com",
        "lifelong_membership": False,
        "university": "Univerzita Karlova",
        "faculty": "Pedagogick\u00e1 fakulta",
        "member_until": "3. 8. 2022",
        "photos_allowed": True,
        "phone": "+420 606 393 494",
        "member_since": "3. 8. 2021",
        "last_prolonged": "3. 8. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Michal",
        "last_name": "Mikeska",
        "email": "michalmikesak@gmail.com",
        "lifelong_membership": False,
        "university": "\u010cesk\u00e9 Vysok\u00e9 U\u010den\u00ed Technick\u00e9",
        "faculty": "Fakulta elektrotechnick\u00e1",
        "member_until": "17. 6. 2022",
        "photos_allowed": True,
        "phone": "+420 734 127 591",
        "member_since": "17. 6. 2021",
        "last_prolonged": "17. 6. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Tom\u00e1\u0161",
        "last_name": "Chrastn\u00fd",
        "email": "chrastny.tom@gmail.com",
        "lifelong_membership": True,
        "university": "",
        "faculty": "undefined",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "+420 770 142 416",
        "member_since": "12. 1. 2021",
        "last_prolonged": "12. 1. 2021",
        "lifetime_since": "12. 1. 2021",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Weitao",
        "last_name": "Wang",
        "email": "weitao.kiwi@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": False,
        "phone": "+421778535063",
        "member_since": "23. 7. 2020",
        "last_prolonged": "23. 7. 2020",
        "lifetime_since": "23. 7. 2020",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "J\u00e1n",
        "last_name": "Matura",
        "email": "jmatura2@seznam.cz",
        "lifelong_membership": True,
        "university": "Nen\u00ed student",
        "faculty": "",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "773 668 304",
        "member_since": "6. 3. 2020",
        "last_prolonged": "6. 3. 2020",
        "lifetime_since": "6. 3. 2020",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Julie",
        "last_name": "\u0160pinkov\u00e1",
        "email": "spinkajulie@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Fakulta humanitn\u00edch studi\u00ed",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "+420 723 270 757",
        "member_since": "10. 4. 2018",
        "last_prolonged": "10. 4. 2018",
        "lifetime_since": "10. 4. 2018",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Mitchell",
        "last_name": "Hoffman",
        "email": "hoffman.mitchell.d.1996@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Fakulta humanitn\u00edch studi\u00ed",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "+420 775 441 045",
        "member_since": "24. 7. 2020",
        "last_prolonged": "24. 7. 2020",
        "lifetime_since": "24. 7. 2020",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Richard",
        "last_name": "Fluxa",
        "email": "hallo.richard.fluxa@seznam.cz",
        "lifelong_membership": True,
        "university": "Jin\u00e1",
        "faculty": "Jin\u00e1",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "604 191 565",
        "member_since": "16. 6. 2020",
        "last_prolonged": "16. 6. 2020",
        "lifetime_since": "16. 6. 2020",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Adam",
        "last_name": "Urb\u00e1nek",
        "email": "urbanekad@seznam.cz",
        "lifelong_membership": True,
        "university": "\u010cesk\u00e9 Vysok\u00e9 U\u010den\u00ed Technick\u00e9",
        "faculty": "Jin\u00e1",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "+420 731 340 104",
        "member_since": "11. 8. 2020",
        "last_prolonged": "11. 8. 2020",
        "lifetime_since": "11. 8. 2020",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Valerio",
        "last_name": "Emanuele",
        "email": "valerioemanuele@post.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "+39 342 022 69 77",
        "member_since": "31. 3. 2022",
        "last_prolonged": "31. 3. 2022",
        "lifetime_since": "31. 3. 2022",
        "paid_application": False,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Ana\u00eblle",
        "last_name": "Jeannin",
        "email": "anaelle0303@gmail.com",
        "lifelong_membership": False,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "13. 10. 2022",
        "photos_allowed": True,
        "phone": "+336 3557 33 30",
        "member_since": "13. 10. 2021",
        "last_prolonged": "13. 10. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Kry\u0161tof",
        "last_name": "Eckhardt",
        "email": "kris147@seznam.cz",
        "lifelong_membership": False,
        "university": "Univerzita Karlova",
        "faculty": "Pedagogick\u00e1 fakulta",
        "member_until": "11. 12. 2022",
        "photos_allowed": True,
        "phone": "+420 601 347 187",
        "member_since": "12. 12. 2021",
        "last_prolonged": "12. 12. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Jakub",
        "last_name": "Kast",
        "email": "kast.jakub@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Matematicko-fyzik\u00e1ln\u00ed fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "725756720",
        "member_since": "1. 5. 2019",
        "last_prolonged": "1. 5. 2019",
        "lifetime_since": "1. 5. 2019",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Luk\u00e1\u0161",
        "last_name": "Dan\u011bk",
        "email": "ludanekas@gmail.com",
        "lifelong_membership": True,
        "university": "\u010cesk\u00e9 Vysok\u00e9 U\u010den\u00ed Technick\u00e9",
        "faculty": "Fakulta informa\u010dn\u00edch technol\u00f3gi\u00ed",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "604833531",
        "member_since": "5. 3. 2019",
        "last_prolonged": "5. 3. 2019",
        "lifetime_since": "5. 3. 2019",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Jana",
        "last_name": "P\u0159iklopilov\u00e1",
        "email": "jana.prik@seznam.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Fakulta humanitn\u00edch studi\u00ed",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "+420 606 811 943",
        "member_since": "16. 11. 2021",
        "last_prolonged": "16. 11. 2021",
        "lifetime_since": "16. 11. 2021",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Krystian",
        "last_name": "Przybysz",
        "email": "krystianprzybysz00@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "+420 736 143 867",
        "member_since": "18. 1. 2022",
        "last_prolonged": "18. 1. 2022",
        "lifetime_since": "18. 1. 2022",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "J\u00e1chym",
        "last_name": "\u010cern\u00fd",
        "email": "blek.jr@gmail.com",
        "lifelong_membership": False,
        "university": "\u010cesk\u00e1 zem\u011bd\u011blsk\u00e1 univerzita",
        "faculty": "Provozn\u011b ekonomick\u00e1 fakulta",
        "member_until": "31. 12. 2022",
        "photos_allowed": True,
        "phone": "+420 608 001 088",
        "member_since": "4. 3. 2019",
        "last_prolonged": "1. 1. 2022",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "J\u00ed\u0159\u00ed",
        "last_name": "Kope\u010dek",
        "email": "jiri.kopecek.1994@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Jin\u00e1",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "",
        "member_since": "6. 8. 2020",
        "last_prolonged": "9. 9. 2021",
        "lifetime_since": "9. 9. 2021",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Jana",
        "last_name": "Ad\u00e1mkov\u00e1",
        "email": "jaadamkova@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Pedagogick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "732488228",
        "member_since": "13. 8. 2011",
        "last_prolonged": "13. 8. 2011",
        "lifetime_since": "13. 8. 2011",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Radka",
        "last_name": "Bauerov\u00e1",
        "email": "radka.bauerova@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Jana Amose Komensk\u00e9ho",
        "faculty": "",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "608834703",
        "member_since": "5. 10. 2010",
        "last_prolonged": "5. 10. 2010",
        "lifetime_since": "5. 10. 2010",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Pavl\u00edna",
        "last_name": "Min\u00e1\u010dov\u00e1",
        "email": "minacova21@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "+420 605 064 661",
        "member_since": "12. 10. 2020",
        "last_prolonged": "12. 10. 2020",
        "lifetime_since": "12. 10. 2020",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Adela",
        "last_name": "Vere\u0161pejov\u00e1",
        "email": "adelaverespejova@gmail.com",
        "lifelong_membership": False,
        "university": "Univerzita Karlova",
        "faculty": "T\u0159et\u00ed L\u00e9k\u00e1\u0159sk\u00e1 fakulta",
        "member_until": "21. 9. 2022",
        "photos_allowed": True,
        "phone": "+421 904 159 158",
        "member_since": "21. 9. 2021",
        "last_prolonged": "21. 9. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Blanca Alonso",
        "last_name": "Goncalves",
        "email": "blanca.alogon@gmail.com",
        "lifelong_membership": False,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "28. 9. 2022",
        "photos_allowed": True,
        "phone": "+34 606 29 06 10",
        "member_since": "28. 9. 2021",
        "last_prolonged": "28. 9. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Jan",
        "last_name": "Dvo\u0159\u00e1\u010dek",
        "email": "jan.honza.dvoracek@gmail.com",
        "lifelong_membership": False,
        "university": "Univerzita Karlova",
        "faculty": "P\u0159\u00edrodov\u011bdeck\u00e1 fakulta",
        "member_until": "4. 8. 2022",
        "photos_allowed": True,
        "phone": "+420 722 184 393",
        "member_since": "4. 8. 2021",
        "last_prolonged": "4. 8. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Tom\u00e1\u0161",
        "last_name": "Hart",
        "email": "tomashart@email.cz",
        "lifelong_membership": False,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "17. 8. 2022",
        "photos_allowed": True,
        "phone": "+420 737 187 265",
        "member_since": "17. 8. 2021",
        "last_prolonged": "17. 8. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Jana",
        "last_name": "Beda\u0148ov\u00e1",
        "email": "jana.bedanova@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Pr\u00e1vnick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "608068744",
        "member_since": "27. 10. 2017",
        "last_prolonged": "27. 10. 2017",
        "lifetime_since": "27. 10. 2017",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Zuzana",
        "last_name": "B\u011blohl\u00e1vkov\u00e1",
        "email": "zuzbelo@yahoo.com",
        "lifelong_membership": True,
        "university": "Univerzita Jana Amose Komensk\u00e9ho",
        "faculty": "",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "775080147",
        "member_since": "26. 10. 2010",
        "last_prolonged": "26. 10. 2010",
        "lifetime_since": "26. 10. 2010",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Martin",
        "last_name": "Benda",
        "email": "benda@ukmedia.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "undefined",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "724541122",
        "member_since": "8. 11. 2010",
        "last_prolonged": "8. 11. 2010",
        "lifetime_since": "8. 11. 2010",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Filip",
        "last_name": "Lambert",
        "email": "filip.zastava@seznam.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "P\u0159\u00edrodov\u011bd\u011bck\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "777 745 034",
        "member_since": "6. 8. 2020",
        "last_prolonged": "7. 8. 2020",
        "lifetime_since": "7. 8. 2020",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Jade",
        "last_name": "MacEwan",
        "email": "jjonsi@hotmail.com",
        "lifelong_membership": True,
        "university": "Jin\u00e1",
        "faculty": "Jin\u00e1",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "+420721847444",
        "member_since": "27. 10. 2021",
        "last_prolonged": "27. 10. 2021",
        "lifetime_since": "27. 10. 2021",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Tereza",
        "last_name": "Horn\u00ed\u010dkov\u00e1",
        "email": "dorian.hornicek@gmail.com",
        "lifelong_membership": False,
        "university": "\u010cesk\u00e9 Vysok\u00e9 U\u010den\u00ed Technick\u00e9",
        "faculty": "Fakulta informa\u010dn\u00edch technol\u00f3gi\u00ed",
        "member_until": "31. 12. 2022",
        "photos_allowed": True,
        "phone": "+420 721 623 251",
        "member_since": "5. 3. 2019",
        "last_prolonged": "1. 1. 2022",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Tereza",
        "last_name": "Mary\u0161kov\u00e1",
        "email": "tereza.maryskova@student.mgvsetin.cz",
        "lifelong_membership": False,
        "university": "Jin\u00e1",
        "faculty": "Jin\u00e1",
        "member_until": "14. 2. 2023",
        "photos_allowed": True,
        "phone": "+420 607 262 910",
        "member_since": "15. 2. 2022",
        "last_prolonged": "15. 2. 2022",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "S\u00e1m\u00ed",
        "last_name": "Salah",
        "email": "sami.n.a.m.salah@gmail.com",
        "lifelong_membership": False,
        "university": "\u010cesk\u00e9 Vysok\u00e9 U\u010den\u00ed Technick\u00e9",
        "faculty": "Fakulta elektrotechnick\u00e1",
        "member_until": "31. 12. 2022",
        "photos_allowed": True,
        "phone": "+420 774 041 072",
        "member_since": "5. 11. 2019",
        "last_prolonged": "1. 1. 2022",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Filip",
        "last_name": "J\u00edra",
        "email": "jira.filip@email.cz",
        "lifelong_membership": True,
        "university": "\u010cesk\u00e9 Vysok\u00e9 U\u010den\u00ed Technick\u00e9",
        "faculty": "Fakulta informa\u010dn\u00edch technol\u00f3gi\u00ed",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "",
        "member_since": "15. 9. 2020",
        "last_prolonged": "15. 9. 2020",
        "lifetime_since": "15. 9. 2020",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Michael",
        "last_name": "Ben\u00ed\u0161ek",
        "email": "michael.benisek@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "737673637",
        "member_since": "2. 5. 2017",
        "last_prolonged": "2. 5. 2017",
        "lifetime_since": "2. 5. 2017",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Emre",
        "last_name": "Ilpars",
        "email": "emreilpars@gmail.com",
        "lifelong_membership": False,
        "university": "Jin\u00e1",
        "faculty": "Jin\u00e1",
        "member_until": "9. 9. 2022",
        "photos_allowed": True,
        "phone": "+420 777 214 593",
        "member_since": "19. 8. 2020",
        "last_prolonged": "9. 9. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Tade\u00e1\u0161",
        "last_name": "Beyer",
        "email": "tadeasbeyer@gmail.com",
        "lifelong_membership": True,
        "university": "Nen\u00ed student",
        "faculty": "",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "773947070",
        "member_since": "16. 12. 2010",
        "last_prolonged": "",
        "lifetime_since": "18. 1. 2011",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Daniel",
        "last_name": "Msallam",
        "email": "daniel.Msallam@seznam.cz",
        "lifelong_membership": False,
        "university": "Univerzita Karlova",
        "faculty": "P\u0159\u00edrodov\u011bdeck\u00e1 fakulta",
        "member_until": "11. 2. 2021",
        "photos_allowed": True,
        "phone": "725763924",
        "member_since": "11. 2. 2020",
        "last_prolonged": "11. 2. 2020",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Zden\u011bk Robin",
        "last_name": "Scholze",
        "email": "zrsch3@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "P\u0159\u00edrodov\u011bd\u011bck\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "724501828",
        "member_since": "28. 3. 2010",
        "last_prolonged": "28. 3. 2010",
        "lifetime_since": "28. 3. 2010",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Jaroslav",
        "last_name": "Bican",
        "email": "bican.jaroslav@seznam.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "732845120",
        "member_since": "1. 10. 2011",
        "last_prolonged": "18. 8. 2017",
        "lifetime_since": "13. 7. 2015",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Nathalie",
        "last_name": "Bourgeois",
        "email": "bourgeois.n@seznam.cz",
        "lifelong_membership": False,
        "university": "Vysok\u00e1 \u0160kola Ekonomick\u00e1",
        "faculty": "Fakulta informa\u010dn\u00edch studi\u00ed",
        "member_until": "6. 8. 2022",
        "photos_allowed": True,
        "phone": "604 520 449",
        "member_since": "6. 8. 2020",
        "last_prolonged": "6. 8. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Marie",
        "last_name": "Lihtarov\u00e1",
        "email": "larskulich.kulisak@gmail.com",
        "lifelong_membership": False,
        "university": "Univerzita Karlova",
        "faculty": "Matematicko-fyzik\u00e1ln\u00ed fakulta",
        "member_until": "5. 10. 2022",
        "photos_allowed": True,
        "phone": "+420 773 247 333",
        "member_since": "5. 10. 2021",
        "last_prolonged": "5. 10. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Erick",
        "last_name": "Camargo",
        "email": "erick95@hotmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Prvn\u00ed L\u00e9k\u00e1\u0159sk\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "774104569",
        "member_since": "19. 10. 2015",
        "last_prolonged": "",
        "lifetime_since": "19. 10. 2015",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Daniela Paola",
        "last_name": "Capponi",
        "email": "skailish@gmail.com",
        "lifelong_membership": True,
        "university": "Nen\u00ed student",
        "faculty": "",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "776722567",
        "member_since": "7. 6. 2010",
        "last_prolonged": "",
        "lifetime_since": "14. 5. 2011",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Denisa Regine",
        "last_name": "Novotn\u00e1",
        "email": "deniska.novotna@centrum.cz",
        "lifelong_membership": False,
        "university": "Nen\u00ed student",
        "faculty": "",
        "member_until": "9. 8. 2022",
        "photos_allowed": True,
        "phone": "722 156 844",
        "member_since": "6. 8. 2020",
        "last_prolonged": "9. 8. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Daniel",
        "last_name": "D\u0159\u00edmal",
        "email": "drimal.d@seznam.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Pedagogick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "724130974",
        "member_since": "20. 12. 2011",
        "last_prolonged": "20. 12. 2011",
        "lifetime_since": "20. 12. 2011",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Jakub",
        "last_name": "Dul\u00ednek",
        "email": "jakub.dulinek@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Fakulta soci\u00e1ln\u00edch v\u011bd",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "773227738",
        "member_since": "8. 4. 2017",
        "last_prolonged": "",
        "lifetime_since": "20. 12. 2011",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Martin-\u0160achar",
        "last_name": "Elis",
        "email": "elis.ms@email.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "721307786",
        "member_since": "19. 5. 2015",
        "last_prolonged": "",
        "lifetime_since": "19. 5. 2015",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Jan 1.",
        "last_name": "Fiala",
        "email": "janfiala1OA@seznam.cz",
        "lifelong_membership": True,
        "university": "Vysok\u00e1 \u0160kola Ekonomick\u00e1",
        "faculty": "Fakulta finan\u010dnictv\u00ed a \u00fa\u010detnictv\u00ed",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "737922087",
        "member_since": "22. 9. 2015",
        "last_prolonged": "",
        "lifetime_since": "22. 9. 2015",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Jan 2.",
        "last_name": "Fiala",
        "email": "honza.fiala@seznam.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Fakulta soci\u00e1ln\u00edch v\u011bd",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "737622731",
        "member_since": "7. 4. 2016",
        "last_prolonged": "",
        "lifetime_since": "7. 4. 2016",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Andrew Philip",
        "last_name": "Fisher",
        "email": "independent_tongue@yahoo.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "608301448",
        "member_since": "15. 8. 2011",
        "last_prolonged": "",
        "lifetime_since": "18. 8. 2013",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Dominik",
        "last_name": "Fojt\u00edk",
        "email": "fojtik.dominik@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "735740221",
        "member_since": "19. 2. 2019",
        "last_prolonged": "19. 2. 2019",
        "lifetime_since": "19. 2. 2019",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "R\u00f3bert",
        "last_name": "Furiel",
        "email": "r.furiel@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Pr\u00e1vnick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "608868534",
        "member_since": "21. 4. 2010",
        "last_prolonged": "21. 4. 2010",
        "lifetime_since": "21. 4. 2010",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Luk\u00e1\u0161",
        "last_name": "Grochol",
        "email": "LukasGrochol@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Prvn\u00ed L\u00e9k\u00e1\u0159sk\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "736219403",
        "member_since": "14. 11. 2013",
        "last_prolonged": "14. 11. 2013",
        "lifetime_since": "14. 11. 2013",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Radim",
        "last_name": "Hejduk",
        "email": "radim.hejduk@yahoo.cz",
        "lifelong_membership": True,
        "university": "Vysok\u00e1 \u0160kola Ekonomick\u00e1",
        "faculty": "N\u00e1rodohospod\u00e1\u0159sk\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "728977394",
        "member_since": "12. 10. 2017",
        "last_prolonged": "12. 10. 2017",
        "lifetime_since": "12. 10. 2017",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Luk\u00e1\u0161",
        "last_name": "Hermann",
        "email": "lukas.hermann@seznam.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Matematicko-fyzik\u00e1ln\u00ed fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "724331222",
        "member_since": "6. 4. 2010",
        "last_prolonged": "",
        "lifetime_since": "26. 5. 2010",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Veronika",
        "last_name": "\u010cert\u00edkov\u00e1",
        "email": "certikova.v@seznam.cz",
        "lifelong_membership": False,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "6. 11. 2022",
        "photos_allowed": True,
        "phone": "+420 774 045 935",
        "member_since": "6. 11. 2021",
        "last_prolonged": "6. 11. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Matthew",
        "last_name": "Evans",
        "email": "Iam.matejevans@gmail.com",
        "lifelong_membership": False,
        "university": "University College Nordjylland",
        "faculty": "Jin\u00e1",
        "member_until": "3. 8. 2022",
        "photos_allowed": True,
        "phone": "+420 736 184 174",
        "member_since": "3. 8. 2021",
        "last_prolonged": "3. 8. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Eva",
        "last_name": "Illia\u0161ov\u00e1",
        "email": "eva.illiasova@gmail.com",
        "lifelong_membership": False,
        "university": "Univerzita Karlova",
        "faculty": "Druh\u00e1 L\u00e9k\u00e1\u0159sk\u00e1 fakulta",
        "member_until": "19. 2. 2023",
        "photos_allowed": True,
        "phone": "+420 605 014 527",
        "member_since": "20. 2. 2022",
        "last_prolonged": "20. 2. 2022",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Veronika",
        "last_name": "Proks",
        "email": "proks.veronika@gmail.com",
        "lifelong_membership": False,
        "university": "Nen\u00ed student",
        "faculty": "",
        "member_until": "28. 3. 2023",
        "photos_allowed": True,
        "phone": "+420 778 971 709",
        "member_since": "29. 3. 2022",
        "last_prolonged": "29. 3. 2022",
        "lifetime_since": "",
        "paid_application": True,
        "approved": False,
        "found_application": True
    },
    {
        "first_name": "Timea",
        "last_name": "Zvol\u00e1nekov\u00e1",
        "email": "timea.zvolanekova@gmail.com",
        "lifelong_membership": False,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "21. 9. 2022",
        "photos_allowed": True,
        "phone": "+421 904 973 740",
        "member_since": "21. 9. 2021",
        "last_prolonged": "21. 9. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Luk\u00e1\u0161",
        "last_name": "Rynt",
        "email": "lukasrynt@gmail.com",
        "lifelong_membership": False,
        "university": "\u010cesk\u00e9 Vysok\u00e9 U\u010den\u00ed Technick\u00e9",
        "faculty": "Fakulta informa\u010dn\u00edch technol\u00f3gi\u00ed",
        "member_until": "17. 6. 2022",
        "photos_allowed": True,
        "phone": "+420 773 088 460",
        "member_since": "17. 6. 2021",
        "last_prolonged": "17. 6. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Daria",
        "last_name": "Gordova",
        "email": "gordovadaria@gmail.com",
        "lifelong_membership": False,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "26. 1. 2022",
        "photos_allowed": True,
        "phone": "723435370",
        "member_since": "4. 3. 2019",
        "last_prolonged": "26. 1. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Jaroslav",
        "last_name": "Schierl",
        "email": "jaroslav.schierl@gmail.com",
        "lifelong_membership": True,
        "university": "Nen\u00ed student",
        "faculty": "P\u0159\u00edrodov\u011bdeck\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "+420 721 081 010",
        "member_since": "13. 10. 2015",
        "last_prolonged": "13. 10. 2015",
        "lifetime_since": "13. 10. 2015",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Viktor",
        "last_name": "Karl\u00ed\u010dek",
        "email": "viki.karlicek@gmail.com",
        "lifelong_membership": False,
        "university": "Univerzita Karlova",
        "faculty": "Fakulta soci\u00e1ln\u00edch v\u011bd",
        "member_until": "31. 12. 2022",
        "photos_allowed": True,
        "phone": "+420 732 355 016",
        "member_since": "7. 5. 2019",
        "last_prolonged": "1. 1. 2022",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Kate\u0159ina",
        "last_name": "Vel\u00ednsk\u00e1",
        "email": "katerinavelinska@gmail.com",
        "lifelong_membership": False,
        "university": "Univerzita Karlova",
        "faculty": "Fakulta humanitn\u00edch studi\u00ed",
        "member_until": "5. 10. 2022",
        "photos_allowed": True,
        "phone": "+420 731 561 063",
        "member_since": "5. 10. 2021",
        "last_prolonged": "5. 10. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Christian Lou",
        "last_name": "Cepe",
        "email": "chcepe@gmail.com",
        "lifelong_membership": True,
        "university": "Nen\u00ed student",
        "faculty": "",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "603 401 295",
        "member_since": "4. 2. 2020",
        "last_prolonged": "4. 2. 2020",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Petr",
        "last_name": "Hnyk",
        "email": "prox.alfa@seznam.cz",
        "lifelong_membership": True,
        "university": "Vysok\u00e1 \u0160kola Ekonomick\u00e1",
        "faculty": "N\u00e1rodohospod\u00e1\u0159sk\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "604864726",
        "member_since": "19. 7. 2011",
        "last_prolonged": "19. 7. 2011",
        "lifetime_since": "19. 7. 2011",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Dian",
        "last_name": "Hrozek",
        "email": "dian.hrozek@gmail.com",
        "lifelong_membership": True,
        "university": "\u010cesk\u00e9 Vysok\u00e9 U\u010den\u00ed Technick\u00e9",
        "faculty": "Fakulta elektrotechnick\u00e1",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "734391594",
        "member_since": "17. 1. 2018",
        "last_prolonged": "",
        "lifetime_since": "28. 12. 2018",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Tom\u00e1\u0161",
        "last_name": "Jan\u00e1\u010dek",
        "email": "tomasjanacek@hotmail.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Fakulta soci\u00e1ln\u00edch v\u011bd",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "605403778",
        "member_since": "2. 11. 2010",
        "last_prolonged": "2. 11. 2010",
        "lifetime_since": "2. 11. 2010",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Martin",
        "last_name": "Jel\u00ednek",
        "email": "martin.jelinek.01@seznam.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "733214470",
        "member_since": "3. 11. 2015",
        "last_prolonged": "3. 11. 2015",
        "lifetime_since": "3. 11. 2015",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Kate\u0159ina",
        "last_name": "Kadav\u00e1",
        "email": "biline@seznam.cz",
        "lifelong_membership": True,
        "university": "Policejn\u00ed akademie \u010cR",
        "faculty": "",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "721417631",
        "member_since": "18. 1. 2011",
        "last_prolonged": "18. 1. 2011",
        "lifetime_since": "18. 1. 2011",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Jan",
        "last_name": "Kade\u0159\u00e1vek",
        "email": "JKaderavek@seznam.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Husitsk\u00e1 teologick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "776408515",
        "member_since": "15. 5. 2015",
        "last_prolonged": "15. 5. 2015",
        "lifetime_since": "15. 5. 2015",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Jakub",
        "last_name": "Kocm\u00e1nek",
        "email": "j.kocmanek@seznam.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Pr\u00e1vnick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "775914355",
        "member_since": "28. 3. 2010",
        "last_prolonged": "28. 3. 2010",
        "lifetime_since": "28. 3. 2010",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Eduard",
        "last_name": "Kop\u00e1\u010dek",
        "email": "werwomit@gmail.com",
        "lifelong_membership": True,
        "university": "",
        "faculty": "undefined",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "777630273",
        "member_since": "12. 11. 2013",
        "last_prolonged": "",
        "lifetime_since": "4. 4. 2017",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Michal",
        "last_name": "Kubelka",
        "email": "michalkubelka16@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "602976169",
        "member_since": "1. 5. 2017",
        "last_prolonged": "",
        "lifetime_since": "28. 5. 2015",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Pavel",
        "last_name": "Ku\u010da",
        "email": "pavel.kuca.cz@gmail.com",
        "lifelong_membership": True,
        "university": "Masarykova univerzita",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "737880936",
        "member_since": "3. 11. 2015",
        "last_prolonged": "",
        "lifetime_since": "12. 10. 2016",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Jan",
        "last_name": "Kundrl\u00edk",
        "email": "jkundrlik@seznam.cz",
        "lifelong_membership": True,
        "university": "\u010cesk\u00e9 Vysok\u00e9 U\u010den\u00ed Technick\u00e9",
        "faculty": "Fakulta jadern\u00e9 fyziky",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "732417226",
        "member_since": "18. 5. 2010",
        "last_prolonged": "18. 5. 2010",
        "lifetime_since": "18. 5. 2010",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Filip",
        "last_name": "\u0160efrna",
        "email": "fsefrna@gmail.com",
        "lifelong_membership": True,
        "university": "Nen\u00ed student",
        "faculty": "",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "776003780",
        "member_since": "4. 11. 2014",
        "last_prolonged": "",
        "lifetime_since": "4. 11. 2014",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "V\u00edt\u011bzslav",
        "last_name": "Sl\u00edva",
        "email": "svestka000@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Fakulta soci\u00e1ln\u00edch v\u011bd",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "776630139",
        "member_since": "28. 3. 2010",
        "last_prolonged": "28. 3. 2010",
        "lifetime_since": "28. 3. 2010",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Hana",
        "last_name": "Soudkov\u00e1",
        "email": "soudkovahana@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Fakulta soci\u00e1ln\u00edch v\u011bd",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "774589924",
        "member_since": "16. 11. 2017",
        "last_prolonged": "",
        "lifetime_since": "3. 4. 2018",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Marcel",
        "last_name": "Souken\u00edk",
        "email": "macek001@gmail.com",
        "lifelong_membership": True,
        "university": "\u010cesk\u00e9 Vysok\u00e9 U\u010den\u00ed Technick\u00e9",
        "faculty": "Fakulta elektrotechnick\u00e1",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "723838004",
        "member_since": "12. 7. 2011",
        "last_prolonged": "12. 7. 2011",
        "lifetime_since": "12. 7. 2011",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Josef",
        "last_name": "\u0160perl",
        "email": "sperl.jos@seznam.cz",
        "lifelong_membership": True,
        "university": "Vysok\u00e1 \u0160kola Ekonomick\u00e1",
        "faculty": "Fakulta finan\u010dnictv\u00ed a \u00fa\u010detnictv\u00ed",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "721111050",
        "member_since": "23. 9. 2015",
        "last_prolonged": "",
        "lifetime_since": "23. 9. 2015",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Tom\u00e1\u0161",
        "last_name": "Stavrovsk\u00fd",
        "email": "tomas.stavrovsky@centrum.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Pr\u00e1vnick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "728949323",
        "member_since": "6. 12. 2016",
        "last_prolonged": "",
        "lifetime_since": "6. 1. 2018",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Barbora",
        "last_name": "Stuhlov\u00e1",
        "email": "barbora.stuhlov\u00e1@email.cz",
        "lifelong_membership": True,
        "university": "",
        "faculty": "Pedagogick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "723282941",
        "member_since": "24. 4. 2017",
        "last_prolonged": "",
        "lifetime_since": "24. 4. 2017",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Miroslav",
        "last_name": "\u0160ubrt",
        "email": "mirek.subrt@email.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Pedagogick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "607817221",
        "member_since": "5. 3. 2013",
        "last_prolonged": "18. 3. 2018",
        "lifetime_since": "18. 3. 2019",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Jakub",
        "last_name": "\u0160v\u00e1b",
        "email": "jakub.svab@email.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Pr\u00e1vnick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "739034993",
        "member_since": "6. 11. 2018",
        "last_prolonged": "",
        "lifetime_since": "6. 11. 2018",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Barbora",
        "last_name": "Szabov\u00e1",
        "email": "barbora.szabov@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": False,
        "phone": "736169393",
        "member_since": "22. 3. 2011",
        "last_prolonged": "22. 3. 2011",
        "lifetime_since": "22. 3. 2011",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Jan",
        "last_name": "Kamenick\u00fd",
        "email": "xkamenickyjan@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "P\u0159\u00edrodov\u011bd\u011bck\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "604126978",
        "member_since": "1. 4. 2019",
        "last_prolonged": "1. 4. 2019",
        "lifetime_since": "1. 4. 2019",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Petra",
        "last_name": "Dolej\u0161ov\u00e1",
        "email": "pe.dolejsova@seznam.cz",
        "lifelong_membership": False,
        "university": "Vysok\u00e1 \u0160kola Ekonomick\u00e1",
        "faculty": "Ekonomika a management",
        "member_until": "21. 1. 2023",
        "photos_allowed": True,
        "phone": "735836465",
        "member_since": "26. 2. 2019",
        "last_prolonged": "21. 1. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Timur",
        "last_name": "Koychiev",
        "email": "koichiev@gmail.ru",
        "lifelong_membership": False,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "30. 8. 2022",
        "photos_allowed": True,
        "phone": "777626743",
        "member_since": "3. 4. 2018",
        "last_prolonged": "30. 8. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "luk\u00e1\u0161",
        "last_name": "palar\u010d\u00edk",
        "email": "lukaspalarcik@seznam.cz",
        "lifelong_membership": False,
        "university": "Univerzita Karlova",
        "faculty": "Fakulta humanitn\u00edch studi\u00ed",
        "member_until": "16. 11. 2022",
        "photos_allowed": True,
        "phone": "+420 601 317 644",
        "member_since": "17. 11. 2021",
        "last_prolonged": "17. 11. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "T\u00e1\u0148a",
        "last_name": "Sin\u00e1",
        "email": "dr.tana.sina@gmail.com",
        "lifelong_membership": False,
        "university": "Veterin\u00e1rn\u00ed a farmaceutick\u00e1 univerzita Brno",
        "faculty": "Fakulta veterin\u00e1rn\u00edho l\u00e9k\u00e1\u0159stv\u00ed",
        "member_until": "19. 8. 2022",
        "photos_allowed": True,
        "phone": "+420 733 117 747",
        "member_since": "19. 8. 2021",
        "last_prolonged": "19. 8. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Petra",
        "last_name": "Koll\u00e1rov\u00e1",
        "email": "ne\u010diteln\u00fd",
        "lifelong_membership": False,
        "university": "Univerzita Karlova",
        "faculty": "Fakulta humanitn\u00edch studi\u00ed",
        "member_until": "15. 11. 2022",
        "photos_allowed": True,
        "phone": "+420 776 810 738",
        "member_since": "16. 11. 2021",
        "last_prolonged": "16. 11. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Kate\u0159ina",
        "last_name": "Z\u00e1rubov\u00e1",
        "email": "kacka.zarubova@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "+420 730 630 945",
        "member_since": "11. 11. 2021",
        "last_prolonged": "11. 11. 2021",
        "lifetime_since": "11. 11. 2021",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Dominik",
        "last_name": "Bub\u00e1k",
        "email": "bubakd@gmail.com",
        "lifelong_membership": True,
        "university": "Jin\u00e1",
        "faculty": "Jin\u00e1",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "+420728669802",
        "member_since": "5. 3. 2022",
        "last_prolonged": "5. 3. 2022",
        "lifetime_since": "5. 3. 2022",
        "paid_application": False,
        "approved": False,
        "found_application": True
    },
    {
        "first_name": "Olga",
        "last_name": "Dzigunova",
        "email": "dzigunova@seznam.cz",
        "lifelong_membership": False,
        "university": "Nen\u00ed student",
        "faculty": "",
        "member_until": "28. 3. 2023",
        "photos_allowed": True,
        "phone": "+420 774 208 535",
        "member_since": "29. 3. 2022",
        "last_prolonged": "29. 3. 2022",
        "lifetime_since": "",
        "paid_application": True,
        "approved": False,
        "found_application": True
    },
    {
        "first_name": "Martin",
        "last_name": "Hol\u00ednec",
        "email": "martinjoa@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "P\u0159\u00edrodov\u011bdeck\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "+421 903 180 609",
        "member_since": "21. 9. 2021",
        "last_prolonged": "21. 9. 2021",
        "lifetime_since": "21. 9. 2021",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Tom\u00e1\u0161",
        "last_name": "Chvojka",
        "email": "chvojkat@vscht.cz",
        "lifelong_membership": True,
        "university": "",
        "faculty": "undefined",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "+420 604 325 035",
        "member_since": "31. 8. 2021",
        "last_prolonged": "31. 8. 2021",
        "lifetime_since": "31. 8. 2021",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Jakub",
        "last_name": "Varva\u0159ovsk\u00fd",
        "email": "varvar@email.cz",
        "lifelong_membership": False,
        "university": "Nen\u00ed student",
        "faculty": "",
        "member_until": "5. 10. 2022",
        "photos_allowed": True,
        "phone": "+420 728 866 907",
        "member_since": "5. 10. 2021",
        "last_prolonged": "5. 10. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Jan",
        "last_name": "T\u0159\u00edska",
        "email": "triska-jan@centrum.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "P\u0159\u00edrodov\u011bd\u011bck\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "731022121",
        "member_since": "8. 11. 2011",
        "last_prolonged": "8. 11. 2011",
        "lifetime_since": "8. 11. 2011",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Dan",
        "last_name": "Ungureanu",
        "email": "afrasiab30@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "776253767",
        "member_since": "14. 9. 2016",
        "last_prolonged": "14. 9. 2016",
        "lifetime_since": "14. 9. 2016",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Petr",
        "last_name": "V\u00e1cha",
        "email": "mr.petrvacha@gmail.com",
        "lifelong_membership": True,
        "university": "Masarykova univerzita",
        "faculty": "Fakulta soci\u00e1ln\u00edch studi\u00ed",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "736678627",
        "member_since": "28. 3. 2010",
        "last_prolonged": "28. 3. 2010",
        "lifetime_since": "28. 3. 2010",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Martin",
        "last_name": "V\u00e1clavek",
        "email": "martin.vaclavek.e1@email.cz",
        "lifelong_membership": True,
        "university": "\u010cesk\u00e9 Vysok\u00e9 U\u010den\u00ed Technick\u00e9",
        "faculty": "Fakulta jadern\u00e9 fyziky",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "739152686",
        "member_since": "14. 9. 2011",
        "last_prolonged": "14. 9. 2011",
        "lifetime_since": "14. 9. 2011",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Ond\u0159ej",
        "last_name": "Vadinsk\u00fd",
        "email": "ondrej.vadinsky@seznam.cz",
        "lifelong_membership": True,
        "university": "Vysok\u00e1 \u0160kola Ekonomick\u00e1",
        "faculty": "Fakulta informa\u010dn\u00edch studi\u00ed",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "",
        "member_since": "19. 5. 2015",
        "last_prolonged": "",
        "lifetime_since": "5. 4. 2016",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Jakub",
        "last_name": "Ve\u010dern\u00edk",
        "email": "xvecj03@vse.cz",
        "lifelong_membership": True,
        "university": "Vysok\u00e1 \u0160kola Ekonomick\u00e1",
        "faculty": "N\u00e1rodohospod\u00e1\u0159sk\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "",
        "member_since": "6. 4. 2010",
        "last_prolonged": "",
        "lifetime_since": "26. 5. 2010",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Dagmar",
        "last_name": "Svobodov\u00e1",
        "email": "D.Svobodova.11@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Pedagogick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "721583667",
        "member_since": "10. 7. 2019",
        "last_prolonged": "25. 8. 2021",
        "lifetime_since": "25. 8. 2021",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Maty\u00e1\u0161",
        "last_name": "Medek",
        "email": "matmedek@volny.cz",
        "lifelong_membership": True,
        "university": "\u010cesk\u00e9 Vysok\u00e9 U\u010den\u00ed Technick\u00e9",
        "faculty": "Fakulta stavebn\u00ed",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "732721469",
        "member_since": "6. 6. 2017",
        "last_prolonged": "20. 9. 2021",
        "lifetime_since": "20. 9. 2021",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "\u0160imon",
        "last_name": "\u00daradn\u00edk",
        "email": "simonuradnik@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "P\u0159\u00edrodov\u011bdeck\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "739376007",
        "member_since": "1. 4. 2019",
        "last_prolonged": "1. 4. 2019",
        "lifetime_since": "1. 4. 2019",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Bronislav",
        "last_name": "Poul",
        "email": "bronislav.poul@seznam.cz",
        "lifelong_membership": False,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "4. 4. 2020",
        "photos_allowed": True,
        "phone": "777053677",
        "member_since": "5. 4. 2016",
        "last_prolonged": "5. 4. 2019",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Milan",
        "last_name": "Krej\u010da",
        "email": "milan.krejca@seznam.cz",
        "lifelong_membership": True,
        "university": "",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": False,
        "phone": "732528825",
        "member_since": "8. 2. 2011",
        "last_prolonged": "",
        "lifetime_since": "28. 5. 2015",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Tereza",
        "last_name": "Zvolsk\u00e1",
        "email": "tereza.zvolska@gmail.com",
        "lifelong_membership": False,
        "university": "Univerzita Karlova",
        "faculty": "Fakulta humanitn\u00edch studi\u00ed",
        "member_until": "3. 4. 2019",
        "photos_allowed": True,
        "phone": "606585460",
        "member_since": "3. 4. 2018",
        "last_prolonged": "3. 4. 2018",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Jan",
        "last_name": "Rozko\u0161n\u00fd",
        "email": "honzarozkosny@seznam.cz",
        "lifelong_membership": True,
        "university": "\u010cesk\u00e9 Vysok\u00e9 U\u010den\u00ed Technick\u00e9",
        "faculty": "Fakulta strojn\u00ed",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "735033323",
        "member_since": "23. 10. 2018",
        "last_prolonged": "23. 10. 2018",
        "lifetime_since": "23. 10. 2018",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Michaela",
        "last_name": "Vlas\u00e1kov\u00e1",
        "email": "vlasakmichaela@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "725914213",
        "member_since": "17. 10. 2017",
        "last_prolonged": "17. 10. 2017",
        "lifetime_since": "17. 10. 2017",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Denisa",
        "last_name": "Zaj\u00edcov\u00e1",
        "email": "zajicovadeni@email.cz",
        "lifelong_membership": False,
        "university": "Univerzita Karlova",
        "faculty": "Fakulta humanitn\u00edch studi\u00ed",
        "member_until": "16. 11. 2022",
        "photos_allowed": True,
        "phone": "+420 608 068 978",
        "member_since": "16. 11. 2021",
        "last_prolonged": "16. 11. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Julie",
        "last_name": "\u0160ebkov\u00e1",
        "email": "jull.sebkova@gmail.com",
        "lifelong_membership": False,
        "university": "Univerzita Karlova",
        "faculty": "Pedagogick\u00e1 fakulta",
        "member_until": "3. 8. 2022",
        "photos_allowed": True,
        "phone": "+420 731 859 415",
        "member_since": "3. 8. 2021",
        "last_prolonged": "3. 8. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Lucie",
        "last_name": "Arendack\u00e1",
        "email": "lucie.arendacka@seznam.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Pr\u00e1vnick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "+420 723 161 347",
        "member_since": "9. 12. 2021",
        "last_prolonged": "9. 12. 2021",
        "lifetime_since": "9. 12. 2021",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Martin",
        "last_name": "Vr\u0161eck\u00fd",
        "email": "vrsecky.martin@email.cz",
        "lifelong_membership": False,
        "university": "Nen\u00ed student",
        "faculty": "",
        "member_until": "27. 12. 2022",
        "photos_allowed": True,
        "phone": "+420 720 315 961",
        "member_since": "28. 12. 2021",
        "last_prolonged": "28. 12. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Michael",
        "last_name": "Jord\u00e1n",
        "email": "jordan.michael@centrum.cz",
        "lifelong_membership": False,
        "university": "Nen\u00ed student",
        "faculty": "",
        "member_until": "31. 12. 2022",
        "photos_allowed": True,
        "phone": "+420 773 121 210",
        "member_since": "5. 11. 2019",
        "last_prolonged": "1. 1. 2022",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Petr",
        "last_name": "\u0160vanda",
        "email": "svanda.petr378@gmail.com",
        "lifelong_membership": False,
        "university": "Univerzita Karlova",
        "faculty": "P\u0159\u00edrodov\u011bdeck\u00e1 fakulta",
        "member_until": "28. 3. 2023",
        "photos_allowed": True,
        "phone": "+420 723 759 846",
        "member_since": "29. 3. 2022",
        "last_prolonged": "29. 3. 2022",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Patrik",
        "last_name": "Korda",
        "email": "pakorda@email.cz",
        "lifelong_membership": False,
        "university": "Univerzita Karlova",
        "faculty": "Fakulta humanitn\u00edch studi\u00ed",
        "member_until": "24. 8. 2022",
        "photos_allowed": True,
        "phone": "----",
        "member_since": "18. 10. 2018",
        "last_prolonged": "24. 8. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Chris",
        "last_name": "Imlaut",
        "email": "denidlo1@email.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Fakulta humanitn\u00edch studi\u00ed",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "+420 704 450 045",
        "member_since": "21. 9. 2021",
        "last_prolonged": "21. 9. 2021",
        "lifetime_since": "21. 9. 2021",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Michal",
        "last_name": "Stavrev",
        "email": "michal.stavrev@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Jana Amose Komensk\u00e9ho",
        "faculty": "Jin\u00e1",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "724 000 229",
        "member_since": "4. 2. 2020",
        "last_prolonged": "4. 2. 2020",
        "lifetime_since": "4. 2. 2020",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Petra",
        "last_name": "Kalensk\u00e1",
        "email": "p.kalenska@seznam.cz",
        "lifelong_membership": False,
        "university": "Univerzita Karlova",
        "faculty": "P\u0159\u00edrodov\u011bdeck\u00e1 fakulta",
        "member_until": "12. 10. 2022",
        "photos_allowed": True,
        "phone": "+420 775 608 257",
        "member_since": "12. 10. 2021",
        "last_prolonged": "12. 10. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Jaroslava",
        "last_name": "Pobudov\u00e1",
        "email": "jarka.pobudova@seznam.cz",
        "lifelong_membership": False,
        "university": "Nen\u00ed student",
        "faculty": "",
        "member_until": "5. 10. 2022",
        "photos_allowed": True,
        "phone": "+420 734 678 859",
        "member_since": "11. 8. 2020",
        "last_prolonged": "5. 10. 2021",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Ruth Jochanan",
        "last_name": "Weiniger",
        "email": "ruth.weiniger@centrum.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "UK",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "777562142",
        "member_since": "13. 8. 2011",
        "last_prolonged": "13. 8. 2011",
        "lifetime_since": "13. 8. 2011",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Ji\u0159\u00ed",
        "last_name": "Kysilka",
        "email": "kysilkaj@centrum.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "P\u0159\u00edrodov\u011bd\u011bck\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "608503124",
        "member_since": "12. 10. 2010",
        "last_prolonged": "",
        "lifetime_since": "26. 5. 2015",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Patrik",
        "last_name": "Lacina",
        "email": "patrik.lacina@gmail.com",
        "lifelong_membership": True,
        "university": "",
        "faculty": "undefined",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "607214433",
        "member_since": "18. 6. 2015",
        "last_prolonged": "",
        "lifetime_since": "18. 6. 2015",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "David",
        "last_name": "Ma\u0159\u00e1k",
        "email": "marakdavid@seznam.cz",
        "lifelong_membership": True,
        "university": "Nen\u00ed student",
        "faculty": "",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "606702918",
        "member_since": "4. 4. 2017",
        "last_prolonged": "4. 4. 2017",
        "lifetime_since": "4. 4. 2017",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Miroslav Daniel",
        "last_name": "Marek",
        "email": "euisgood@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "604931609",
        "member_since": "25. 10. 2011",
        "last_prolonged": "",
        "lifetime_since": "26. 2. 2013",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Petr",
        "last_name": "Martin\u016f",
        "email": "martinup436@seznam.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "733271440",
        "member_since": "3. 4. 2018",
        "last_prolonged": "3. 4. 2018",
        "lifetime_since": "3. 4. 2018",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Toni",
        "last_name": "Matikainen",
        "email": "toni.matikainen@helsinki.fi",
        "lifelong_membership": True,
        "university": "Nen\u00ed student",
        "faculty": "undefined",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "+358440936700",
        "member_since": "17. 10. 2017",
        "last_prolonged": "17. 10. 2017",
        "lifetime_since": "17. 10. 2017",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Petr",
        "last_name": "Melni\u010duk",
        "email": "pemel@atlas.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Pr\u00e1vnick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "739330956",
        "member_since": "7. 5. 2010",
        "last_prolonged": "7. 5. 2010",
        "lifetime_since": "7. 5. 2010",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Daniel",
        "last_name": "Mencl",
        "email": "daniel.mencl11@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "604723559",
        "member_since": "22. 10. 2015",
        "last_prolonged": "",
        "lifetime_since": "22. 10. 2015",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Jakub",
        "last_name": "M\u00edl",
        "email": "kubamil99@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "P\u0159\u00edrodov\u011bdeck\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "737343447",
        "member_since": "22. 11. 2018",
        "last_prolonged": "22. 11. 2018",
        "lifetime_since": "22. 11. 2018",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Jan",
        "last_name": "Mor\u00e1vek",
        "email": "jan.moravek@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Fakulta soci\u00e1ln\u00edch v\u011bd",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "604252309",
        "member_since": "6. 3. 2012",
        "last_prolonged": "",
        "lifetime_since": "16. 6. 2015",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Richard",
        "last_name": "Mo\u0161ko",
        "email": "richard.mosko@gmail.com",
        "lifelong_membership": True,
        "university": "Nen\u00ed student",
        "faculty": "",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "",
        "member_since": "5. 3. 2019",
        "last_prolonged": "5. 3. 2019",
        "lifetime_since": "5. 3. 2019",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Mihad",
        "last_name": "Mujanovi\u010d",
        "email": "mihadm@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "605222558",
        "member_since": "8. 10. 2011",
        "last_prolonged": "8. 10. 2011",
        "lifetime_since": "8. 10. 2011",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Luk\u00e1\u0161",
        "last_name": "N\u00e1dvorn\u00edk",
        "email": "nadvornik.lukas@seznam.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Matematicko-fyzik\u00e1ln\u00ed fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "728987499",
        "member_since": "6. 4. 2010",
        "last_prolonged": "",
        "lifetime_since": "26. 5. 2010",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Tom\u00e1\u0161",
        "last_name": "Nov\u00e1k",
        "email": "kuvly@icloud.com",
        "lifelong_membership": True,
        "university": "Nen\u00ed student",
        "faculty": "",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "737856837",
        "member_since": "24. 10. 2017",
        "last_prolonged": "24. 10. 2017",
        "lifetime_since": "24. 10. 2017",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Adam",
        "last_name": "O\u0161\u0165\u00e1dal",
        "email": "adam@spyboy.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Fakulta soci\u00e1ln\u00edch v\u011bd",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "608115407",
        "member_since": "6. 4. 2010",
        "last_prolonged": "6. 4. 2010",
        "lifetime_since": "6. 4. 2010",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Petr",
        "last_name": "P\u00e1vek",
        "email": "petr.pavek@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Fakulta soci\u00e1ln\u00edch v\u011bd",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "728141668",
        "member_since": "28. 3. 2010",
        "last_prolonged": "28. 3. 2010",
        "lifetime_since": "28. 3. 2010",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Karel",
        "last_name": "Pavlica",
        "email": "karel.pavlica@gmail.com",
        "lifelong_membership": True,
        "university": "Ostravsk\u00e1 univerzita",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "773088158",
        "member_since": "25. 5. 2010",
        "last_prolonged": "25. 5. 2010",
        "lifetime_since": "25. 5. 2010",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "David",
        "last_name": "Pavlorek",
        "email": "d.pavlorek@seznam.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "776205113",
        "member_since": "12. 8. 2017",
        "last_prolonged": "12. 8. 2017",
        "lifetime_since": "12. 8. 2017",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Matej",
        "last_name": "Pet\u00f6cz",
        "email": "mpetocz@gmail.com",
        "lifelong_membership": True,
        "university": "Vysok\u00e1 \u0160kola Ekonomick\u00e1",
        "faculty": "N\u00e1rodohospod\u00e1\u0159sk\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "421902883",
        "member_since": "4. 10. 2011",
        "last_prolonged": "",
        "lifetime_since": "13. 7. 2015",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Kamil",
        "last_name": "Pikal",
        "email": "kamilpikal@post.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Fakulta soci\u00e1ln\u00edch v\u011bd",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "723700521",
        "member_since": "28. 12. 2015",
        "last_prolonged": "28. 12. 2015",
        "lifetime_since": "28. 12. 2015",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Michael",
        "last_name": "Pokorn\u00fd",
        "email": "pok@rny.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Matematicko-fyzik\u00e1ln\u00ed fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "720182089",
        "member_since": "1. 10. 2013",
        "last_prolonged": "1. 10. 2013",
        "lifetime_since": "1. 10. 2013",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Anton\u00edn",
        "last_name": "Policar",
        "email": "sv.tonik@seznam.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "773999681",
        "member_since": "27. 6. 2011",
        "last_prolonged": "27. 6. 2011",
        "lifetime_since": "27. 6. 2011",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Tom\u00e1\u0161",
        "last_name": "Proch\u00e1zka",
        "email": "tomuf@seznam.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Matematicko-fyzik\u00e1ln\u00ed fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "607812201",
        "member_since": "11. 10. 2011",
        "last_prolonged": "11. 10. 2011",
        "lifetime_since": "11. 10. 2011",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Jan David",
        "last_name": "Reitschl\u00e4ger",
        "email": "david.rt@seznam.cz",
        "lifelong_membership": True,
        "university": "Jiho\u010desk\u00e1 univerzita",
        "faculty": "undefined",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "732572051",
        "member_since": "9. 3. 2015",
        "last_prolonged": "9. 3. 2015",
        "lifetime_since": "9. 3. 2015",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Jan",
        "last_name": "Wintr",
        "email": "wintr@prf.cuni.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Pr\u00e1vnick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "777027914",
        "member_since": "30. 3. 2010",
        "last_prolonged": "",
        "lifetime_since": "8. 11. 2010",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "V\u011bra",
        "last_name": "\u017demli\u010dkov\u00e1",
        "email": "v.zemlickova@seznam.cz",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Filozofick\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "606177814",
        "member_since": "6. 4. 2010",
        "last_prolonged": "6. 4. 2010",
        "lifetime_since": "6. 4. 2010",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Radek",
        "last_name": "Zimmermann",
        "email": "randyz1986@gmail.com",
        "lifelong_membership": True,
        "university": "",
        "faculty": "undefined",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "736176673",
        "member_since": "22. 10. 2014",
        "last_prolonged": "14. 10. 2016",
        "lifetime_since": "26. 10. 2017",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Mat\u011bj",
        "last_name": "Koubek",
        "email": "koubekmatej1@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "P\u0159\u00edrodov\u011bdeck\u00e1 fakulta",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "+420 720 682 261",
        "member_since": "16. 11. 2021",
        "last_prolonged": "16. 11. 2021",
        "lifetime_since": "16. 11. 2021",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Katar\u00edna",
        "last_name": "Kozov\u00e1",
        "email": "katarinakozov\u00e100@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "Fakulta humanitn\u00edch studi\u00ed",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "+420 607 644 918",
        "member_since": "9. 12. 2021",
        "last_prolonged": "9. 12. 2021",
        "lifetime_since": "9. 12. 2021",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Jakub",
        "last_name": "Troj\u00e1nek",
        "email": "jakubtrojanek@gmail.com",
        "lifelong_membership": True,
        "university": "Nen\u00ed student",
        "faculty": "",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "+420 792 300 493",
        "member_since": "18. 1. 2022",
        "last_prolonged": "18. 1. 2022",
        "lifetime_since": "18. 1. 2022",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Martin",
        "last_name": "Pelc",
        "email": "martin.pelc3@gmail.com",
        "lifelong_membership": False,
        "university": "Univerzita Hradec Kr\u00e1lov\u00e9",
        "faculty": "Jin\u00e1",
        "member_until": "31. 12. 2022",
        "photos_allowed": True,
        "phone": "+420 739 774 481",
        "member_since": "2. 4. 2019",
        "last_prolonged": "1. 1. 2022",
        "lifetime_since": "",
        "paid_application": True,
        "approved": True,
        "found_application": True
    },
    {
        "first_name": "Ester",
        "last_name": "Dohn\u00e1lkov\u00e1",
        "email": "ester.dohnalkova@gmail.com",
        "lifelong_membership": True,
        "university": "Univerzita Karlova",
        "faculty": "UK",
        "member_until": "--",
        "photos_allowed": True,
        "phone": "+420 737 968 602",
        "member_since": "2. 4. 2022",
        "last_prolonged": "2. 4. 2022",
        "lifetime_since": "2. 4. 2022",
        "paid_application": True,
        "approved": True,
        "found_application": True
    }
]


class Command(BaseCommand):
    help = 'help'

    def handle(self, *args, **options):
        universities = []
        faculties = []

        for member in members:
            if member.get("university"):
                universities.append(member.get("university"))
            if member.get("faculty"):
                faculties.append(member.get("faculty"))

        universities = list(dict.fromkeys(universities))
        faculties = list(dict.fromkeys(faculties))

        for uni in universities:
            obj = University.objects.create(name=uni)
            obj.save()

        for fac in faculties:
            obj = Faculty.objects.create(name=fac)
            obj.save()